#!/bin/bash

PYTHON_PARSER="$HOME/.config/niri/scripts/cheatsheet_parser.py"
RAW_LIST=$(python3 "$PYTHON_PARSER")

# Kolom: key \t title \t cmd
# Tampilkan kolom 1 dan 2 ke fuzzel
SELECTED=$(echo "$RAW_LIST" | cut -f1,2 | fuzzel --dmenu \
    --tabs=25 \
    --width 60 \
    --lines 15 \
    --prompt "󰘳 ")

if [ -n "$SELECTED" ]; then
    T_SEARCH=$(echo "$SELECTED" | cut -f2 | xargs)

    COMMAND=$(echo "$RAW_LIST" | awk -F'\t' -v t="$T_SEARCH" \
        '$2 == t {print $3; exit}')

    [ -n "$COMMAND" ] && sh -c "$COMMAND"
fi
