#!/bin/bash
PYTHON_PARSER="$HOME/.config/niri/scripts/cheatsheet_parser.py"

RAW_LIST=$(python3 "$PYTHON_PARSER")

SELECTED=$(echo "$RAW_LIST" | awk -F ' │ ' '{printf "%-30s │ %s\n", $1, $2}' | tofi --width 40% --height 50%)

if [ -n "$SELECTED" ]; then
    KEY_ONLY=$(echo "$SELECTED" | awk -F ' │ ' '{print $1}' | xargs)
    COMMAND=$(echo "$RAW_LIST" | grep "^$KEY_ONLY" | awk -F ' │ ' '{print $3}' | head -n 1)
    sh -c "$COMMAND"
fi
