#!/usr/bin/fish

# Mengambil list clipboard, memformat tampilan, dan memproses pilihan
cliphist list | \
fuzzel --dmenu --prompt="󱘟  " | \
awk '{print $1}' | \
cliphist decode | \
wl-copy

# Menjalankan simulasi paste (Ctrl+V)
wtype -M ctrl v -m ctrl