#!/usr/bin/env fish

set selected (
    cliphist list \
    | cut -f2- \
    | fuzzel --dmenu --prompt="󱘟  "
)

if test -n "$selected"

    set clip_id (
        cliphist list \
        | awk -F '\t' -v selected="$selected" '
            $2 == selected {
                print $1
                exit
            }
        '
    )

    cliphist decode $clip_id | wl-copy

    sleep 0.2

    wtype -M ctrl -k v -m ctrl
end
