#!/bin/sh
cliphist list | awk -F'\t' '{print $2 "                                         " $1}' | \
tofi --prompt-text "󱘟  " | \
awk '{print $NF}' | tr -d '\n' | cliphist decode | wl-copy && wtype -M ctrl v -m ctrldmesg | grep -i "Memory:"
