#!/usr/bin/env bash

MODE="${1:-sink}"

IC_DIR="$HOME/.config/assets"
ID_FILE="/tmp/osd-$MODE.id"
TIMEOUT=3000

# drain stdin only if piped
[[ -p /dev/stdin ]] && cat >/dev/null

source ~/.config/niri/scripts/utils

case "$MODE" in
  sink)
    NODE="@DEFAULT_AUDIO_SINK@"
    TITLE="Volume"

    INFO=$(wpctl get-volume "$NODE")
    VOL=$(echo "$INFO" | awk '{printf "%d", $2 * 100}')

    if echo "$INFO" | grep -q MUTED; then
      notify_replace title="$TITLE ${VOL}% (Muted)" progress=$VOL icon="$IC_DIR/ic-volume-mute.svg"
    else
      notify_replace title="$TITLE ${VOL}%" progress=$VOL icon="$IC_DIR/ic-volume-up.svg"
    fi
    ;;
  source)
    NODE="@DEFAULT_AUDIO_SOURCE@"
    TITLE="Microphone"

    INFO=$(wpctl get-volume "$NODE")
    VOL=$(echo "$INFO" | awk '{printf "%d", $2 * 100}')

    if echo "$INFO" | grep -q MUTED; then
      notify_replace title="$TITLE ${VOL}% (Muted)" progress=$VOL icon="$IC_DIR/ic-mic-off.svg"
    else
      notify_replace title="$TITLE ${VOL}%" progress=$VOL icon="$IC_DIR/ic-mic.svg"
    fi
    ;;
  brightness)
    CUR=$(brightnessctl get)
    MAX=$(brightnessctl max)
    PCT=$(( CUR * 100 / MAX ))

    notify_replace title="Brightness ${PCT}%" progress=$PCT icon="$IC_DIR/ic-brightness.svg"
    ;;
  *)
    exit 0
    ;;
esac