# Global Settings
anchor=top
dpi-aware=yes
terminal=alacritty
horizontal-pad=12
inner-pad=8
dpi-aware=no
width=40
lines=15
y-margin=10
placeholder=Search

# UI
font=monospace:size=11
prompt="󰍉 "
terminal=kitty
layer=overlay

[colors]
background=181818ff
input=949494ff
text=949494ff
match=89b4faff
selection=00000000
selection-text=89b4faff
selection-match=89b4faff
border=2a2a2aff
placeholder=454545ff
prompt=d4d4d4ff

[border]
width=1
radius=8